Log: [7a435853-5581-4179-9f53-bd7ffe9ea66d:2025-04-15T11:52:33.893878+0300 - INFO - Request /docs successful ]
Log: [b3ac4af9-4276-4958-b3d3-13d23a205b0a:2025-04-15T11:52:33.991361+0300 - INFO - Request /openapi.json successful ]
Log: [46436743-ff8a-4cf5-bafe-9c03a605fd4e:2025-04-20T14:28:02.776770+0300 - INFO - Request /docs successful ]
Log: [f34bcaad-64e9-4180-8cb1-79a1b9ffd168:2025-04-20T14:28:04.673830+0300 - INFO - Request /openapi.json successful ]
Log: [421efc75-1e74-47f9-a6c2-95f0a4c53158:2025-04-20T15:01:02.185514+0300 - INFO - Request /docs successful ]
Log: [9fcbe1b0-92cf-48d1-a421-e280b5beeaf5:2025-04-20T15:01:02.311468+0300 - INFO - Request /openapi.json successful ]
Log: [5b6b4541-a205-46dd-a225-aeefb10b8d66:2025-04-20T15:03:33.181023+0300 - INFO - Request / successful ]
Log: [cf6dc230-cd26-497b-8bd3-e62747d82565:2025-04-20T15:23:58.912725+0300 - INFO - Request / successful ]
Log: [34ee788a-28de-490c-8ea3-8bbef5ef7606:2025-04-20T15:23:58.951067+0300 - WARNING - /favicon.ico - request failed]
Log: [9ea2b785-a565-44ee-963f-081198d5bf9a:2025-04-20T15:24:00.970218+0300 - INFO - Request /docs successful ]
Log: [b31ef330-c59d-492d-ae65-9173be9d1a82:2025-04-20T15:24:14.953726+0300 - INFO - Request / successful ]
Log: [1dee0d34-5f0b-487a-a666-115b4e396f43:2025-05-14T14:45:23.487000+0300 - INFO - Request /docs successful ]
Log: [95bba096-2b14-4ef4-a159-e74c720173d1:2025-05-14T14:45:26.570733+0300 - INFO - Request /openapi.json successful ]
Log: [8ce366b1-f2c6-4b96-9a37-a098fd1377ae:2025-05-14T14:46:10.145977+0300 - WARNING - /categories/ - request failed]
Log: [7172c38f-4d9c-4dd8-9206-21220332f63f:2025-05-14T14:46:42.654310+0300 - INFO - Request /auth/token successful ]
Log: [1e3c25bd-1fe2-4753-b6b2-ec551e2205ee:2025-05-14T14:52:45.791345+0300 - ERROR - Request to /categories/ failed: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: INSERT или UPDATE в таблице "categories" нарушает ограничение внешнего ключа "categories_parent_id_fkey"
DETAIL:  Ключ (parent_id)=(0) отсутствует в таблице "categories".
[SQL: INSERT INTO categories (name, slug, parent_id, is_active) VALUES ($1::VARCHAR, $2::VARCHAR, $3::INTEGER, $4::BOOLEAN) RETURNING categories.id]
[parameters: ('string', 'string', 0, True)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)]
Log: [9913240f-f8ea-4589-be0b-89017e3f0613:2025-05-14T14:54:35.103609+0300 - ERROR - Request to /categories/ failed: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: INSERT или UPDATE в таблице "categories" нарушает ограничение внешнего ключа "categories_parent_id_fkey"
DETAIL:  Ключ (parent_id)=(1) отсутствует в таблице "categories".
[SQL: INSERT INTO categories (name, slug, parent_id, is_active) VALUES ($1::VARCHAR, $2::VARCHAR, $3::INTEGER, $4::BOOLEAN) RETURNING categories.id]
[parameters: ('string', 'string', 1, True)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)]
Log: [1e086c6c-2dfc-4079-a02b-8b7e3fb77332:2025-05-14T14:55:09.697538+0300 - WARNING - /products/ - request failed]
Log: [4cfb9bdf-eeae-4419-ab82-e03e92914526:2025-05-14T14:55:36.535966+0300 - ERROR - Request to /categories/ failed: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: INSERT или UPDATE в таблице "categories" нарушает ограничение внешнего ключа "categories_parent_id_fkey"
DETAIL:  Ключ (parent_id)=(0) отсутствует в таблице "categories".
[SQL: INSERT INTO categories (name, slug, parent_id, is_active) VALUES ($1::VARCHAR, $2::VARCHAR, $3::INTEGER, $4::BOOLEAN) RETURNING categories.id]
[parameters: ('string', 'string', 0, True)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)]
Log: [e72a02c5-d731-4096-bff9-9086d960dc0d:2025-05-14T14:56:04.184321+0300 - INFO - Request /categories/ successful ]
Log: [42acb4f1-8c33-42c3-b1c7-cdc7e6b74a8c:2025-05-14T14:56:23.181593+0300 - INFO - Request /categories/ successful ]
Log: [bd7807eb-5ed6-4047-a886-33af10a5123a:2025-05-14T14:56:46.574499+0300 - WARNING - /products/ - request failed]
Log: [372b3844-a990-4f5a-9033-8e43d73adf71:2025-05-14T14:57:05.286999+0300 - INFO - Request /products/ successful ]
Log: [472e4ab8-675e-4df6-a799-cbd810fd8e5a:2025-05-14T14:57:17.787208+0300 - INFO - Request /products/ successful ]
Log: [7f23e89f-10c9-4fbb-82cc-f7061f5c8356:2025-05-14T14:57:26.525331+0300 - WARNING - /products/ - request failed]
Log: [24921fe7-237a-48d4-bfe0-88ac1105a23e:2025-05-14T14:57:46.748918+0300 - INFO - Request /categories/ successful ]
Log: [e52ee706-12f3-4d6f-bfc4-36ad0bfd465a:2025-05-14T14:58:22.762108+0300 - INFO - Request /products/ successful ]
Log: [fe0f2d98-5f5d-464e-ad38-f223df1b6f7f:2025-05-14T14:58:35.208067+0300 - INFO - Request /categories/ successful ]
Log: [04670379-c507-4c49-8acb-65c8baf3d16c:2025-05-14T14:59:36.087667+0300 - ERROR - Request to /categories/ failed: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: INSERT или UPDATE в таблице "categories" нарушает ограничение внешнего ключа "categories_parent_id_fkey"
DETAIL:  Ключ (parent_id)=(1) отсутствует в таблице "categories".
[SQL: INSERT INTO categories (name, slug, parent_id, is_active) VALUES ($1::VARCHAR, $2::VARCHAR, $3::INTEGER, $4::BOOLEAN) RETURNING categories.id]
[parameters: ('string', 'string', 1, True)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)]
Log: [0626d8cf-faeb-4b22-b77c-12b47f9d6d62:2025-05-14T14:59:44.152327+0300 - ERROR - Request to /categories/ failed: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: INSERT или UPDATE в таблице "categories" нарушает ограничение внешнего ключа "categories_parent_id_fkey"
DETAIL:  Ключ (parent_id)=(0) отсутствует в таблице "categories".
[SQL: INSERT INTO categories (name, slug, parent_id, is_active) VALUES ($1::VARCHAR, $2::VARCHAR, $3::INTEGER, $4::BOOLEAN) RETURNING categories.id]
[parameters: ('string', 'string', 0, True)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)]
Log: [b362cc99-0815-4957-a03a-98e04a3634f0:2025-05-14T15:07:41.575296+0300 - INFO - Request /docs successful ]
Log: [c31721de-ffe6-4d3b-a79b-4a7a238e66eb:2025-05-14T15:07:41.696828+0300 - INFO - Request /openapi.json successful ]
Log: [ae2a0728-b728-4e5c-98c9-46abe5cbccfa:2025-05-14T15:07:49.750300+0300 - WARNING - /categories/ - request failed]
Log: [89065b3d-1bec-4115-bce5-bef7cb1378ac:2025-05-14T15:07:51.300255+0300 - WARNING - /categories/ - request failed]
Log: [ef3cd622-4bc2-4e55-bd6a-1e14466b8b0e:2025-05-14T15:08:03.235758+0300 - INFO - Request /auth/token successful ]
Log: [90e23466-fea8-4355-a75f-dbba7cc996b4:2025-05-14T15:08:05.569611+0300 - ERROR - Request to /categories/ failed: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: INSERT или UPDATE в таблице "categories" нарушает ограничение внешнего ключа "categories_parent_id_fkey"
DETAIL:  Ключ (parent_id)=(0) отсутствует в таблице "categories".
[SQL: INSERT INTO categories (name, slug, parent_id, is_active) VALUES ($1::VARCHAR, $2::VARCHAR, $3::INTEGER, $4::BOOLEAN) RETURNING categories.id]
[parameters: ('string', 'string', 0, True)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)]
Log: [9f7e4703-5ae7-47c9-802b-fc68573ba396:2025-05-14T15:10:05.034842+0300 - ERROR - Request to /categories/ failed: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: INSERT или UPDATE в таблице "categories" нарушает ограничение внешнего ключа "categories_parent_id_fkey"
DETAIL:  Ключ (parent_id)=(1) отсутствует в таблице "categories".
[SQL: INSERT INTO categories (name, slug, parent_id, is_active) VALUES ($1::VARCHAR, $2::VARCHAR, $3::INTEGER, $4::BOOLEAN) RETURNING categories.id]
[parameters: ('string', 'string', 1, True)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)]
Log: [84d6417b-2468-4864-b5da-d6d4ccc072ef:2025-05-14T15:10:43.161315+0300 - WARNING - /products/ - request failed]
Log: [d74f8057-b409-4a9e-9b56-8f13067025e7:2025-05-14T15:20:10.107152+0300 - INFO - Request /categories/ successful ]
Log: [132b0a48-6de7-4615-af76-d7732d014ba4:2025-05-14T15:20:17.201431+0300 - INFO - Request /categories/ successful ]
Log: [d2cbb517-b265-4d57-aab2-c8cb0f2dba23:2025-05-14T15:20:23.862936+0300 - INFO - Request /categories/ successful ]
Log: [93c716af-090f-443d-8c67-ff6fd4fcc6c6:2025-05-14T15:20:44.177607+0300 - INFO - Request /products/ successful ]
Log: [33e1265c-0e84-4d6b-8b2b-6da7dfa3775a:2025-05-14T22:43:34.790254+0000 - WARNING - /admin - request failed]
Log: [bfa8f583-9e81-43ac-9bb5-209d0700bd93:2025-05-14T22:43:34.944437+0000 - WARNING - /favicon.ico - request failed]
Log: [43f64dc3-c251-4367-89c3-56d802a7ba57:2025-05-14T22:44:15.532225+0000 - ERROR - Request to / failed: 'NoneType' object has no attribute 'Redis']
Log: [7a4ab01b-dabc-482f-8fb7-bbc885ff0293:2025-05-14T22:45:44.948887+0000 - ERROR - Request to / failed: 'NoneType' object has no attribute 'Redis']
Log: [b1f13603-aab5-4625-9b85-f906d063f321:2025-05-14T22:45:53.728395+0000 - WARNING - /swagger - request failed]
Log: [f2fa2431-0c31-433c-9bf9-a0d013a74ce8:2025-05-14T22:46:01.979015+0000 - INFO - Request /docs successful ]
Log: [342a40d8-341d-48e2-90cf-14c5694fa18c:2025-05-14T22:46:02.804137+0000 - INFO - Request /openapi.json successful ]
Log: [a3c96fe2-2827-41e1-aa71-c1714d2c499b:2025-05-14T22:46:15.278858+0000 - WARNING - /categories/ - request failed]
Log: [cf39e371-eb45-4835-abc5-0b39e8d5b9cf:2025-05-14T22:46:33.506158+0000 - ERROR - Request to /auth/token failed: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)]
Log: [b024cb8a-5657-4916-b763-6172a2839060:2025-05-14T22:46:37.044070+0000 - ERROR - Request to /auth/token failed: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)]
Log: [e3ddb3f1-ca83-48b2-91bb-afc9ab0a2b4b:2025-05-14T22:48:57.590212+0000 - ERROR - Request to /auth/token failed: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "users" does not exist
[SQL: SELECT users.id, users.first_name, users.last_name, users.username, users.email, users.hashed_password, users.is_active, users.is_admin, users.is_supplier, users.is_customer 
FROM users 
WHERE users.username = $1::VARCHAR]
[parameters: ('string',)]
(Background on this error at: https://sqlalche.me/e/20/f405)]
Log: [057a93b8-772f-41ef-9d55-462ae4374fc7:2025-05-14T22:49:16.929828+0000 - INFO - Request /docs successful ]
Log: [99665bcf-01c4-48dd-b13e-ed73833eebe1:2025-05-14T22:49:17.051346+0000 - INFO - Request /openapi.json successful ]
Log: [732cc85a-6907-42fa-91a8-a8561a816f45:2025-05-14T22:49:26.751310+0000 - ERROR - Request to /auth/token failed: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "users" does not exist
[SQL: SELECT users.id, users.first_name, users.last_name, users.username, users.email, users.hashed_password, users.is_active, users.is_admin, users.is_supplier, users.is_customer 
FROM users 
WHERE users.username = $1::VARCHAR]
[parameters: ('string',)]
(Background on this error at: https://sqlalche.me/e/20/f405)]
Log: [9fa2c783-e186-4295-918c-0c8e03414472:2025-05-14T22:51:13.926321+0000 - ERROR - Request to /auth/ failed: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "users" does not exist
[SQL: INSERT INTO users (first_name, last_name, username, email, hashed_password, is_active, is_admin, is_supplier, is_customer) VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::BOOLEAN, $7::BOOLEAN, $8::BOOLEAN, $9::BOOLEAN) RETURNING users.id]
[parameters: ('string', 'string', 'string', 'string', '$2b$12$LPwuXiCoL2G15dsFO9ri0eZh5MB.EGhfnT4FFn4QDDKb22KelwXMS', True, False, False, True)]
(Background on this error at: https://sqlalche.me/e/20/f405)]
Log: [5024fde2-dde2-4e92-83be-e1176bc212c2:2025-05-14T22:52:45.315583+0000 - ERROR - Request to /auth/ failed: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "users" does not exist
[SQL: INSERT INTO users (first_name, last_name, username, email, hashed_password, is_active, is_admin, is_supplier, is_customer) VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::BOOLEAN, $7::BOOLEAN, $8::BOOLEAN, $9::BOOLEAN) RETURNING users.id]
[parameters: ('string', 'string', 'string', 'string@gmail.com', '$2b$12$wICikc.Go.unzYIOSKSgoeZ3pMz9Ty3OlsxSrgor3J9W3TmwoX3Bu', True, False, False, True)]
(Background on this error at: https://sqlalche.me/e/20/f405)]
Log: [e9e154f1-33e9-42c2-b279-694f75aae010:2025-05-14T22:58:33.230345+0000 - INFO - Request /docs successful ]
Log: [c5115ab9-fe61-4cdb-be73-6e4d94ccbf6a:2025-05-14T22:58:33.345882+0000 - INFO - Request /openapi.json successful ]
Log: [77a084fb-b384-4229-85a5-3a2bbe43cfb5:2025-05-14T22:58:39.553904+0000 - ERROR - Request to /auth/ failed: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "users" does not exist
[SQL: INSERT INTO users (first_name, last_name, username, email, hashed_password, is_active, is_admin, is_supplier, is_customer) VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::BOOLEAN, $7::BOOLEAN, $8::BOOLEAN, $9::BOOLEAN) RETURNING users.id]
[parameters: ('string', 'string', 'string', 'string', '$2b$12$qPQZEmCU8e0vlCFcToR30ekO3eEHXDZVcdRMht3yQuuxLwfv1BwL6', True, False, False, True)]
(Background on this error at: https://sqlalche.me/e/20/f405)]
Log: [96d6f2b7-b569-487a-a7d0-65319411ac98:2025-05-14T22:59:18.235328+0000 - INFO - Request /docs successful ]
Log: [956ea43b-c1eb-4183-b673-5d5fab2fcf3c:2025-05-14T22:59:18.327368+0000 - INFO - Request /openapi.json successful ]
Log: [b92de97b-1103-4a2f-80ba-8cd638ee371f:2025-05-14T22:59:21.844039+0000 - ERROR - Request to /auth/ failed: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "users" does not exist
[SQL: INSERT INTO users (first_name, last_name, username, email, hashed_password, is_active, is_admin, is_supplier, is_customer) VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::BOOLEAN, $7::BOOLEAN, $8::BOOLEAN, $9::BOOLEAN) RETURNING users.id]
[parameters: ('string', 'string', 'string', 'string', '$2b$12$ura6XtJsovVWHBGJWd47bO6v9cY8MPf/UnGfktQVfq1vrzvcDrM2W', True, False, False, True)]
(Background on this error at: https://sqlalche.me/e/20/f405)]
Log: [2a339eb8-54e4-45a6-9f3b-4a8d78fc3427:2025-05-14T23:03:40.844865+0000 - INFO - Request /docs successful ]
Log: [67c363eb-2eda-4237-a3ed-d3600336e4d9:2025-05-14T23:03:40.909783+0000 - INFO - Request /openapi.json successful ]
Log: [08bb97e3-d1ff-48c0-90c3-2093538cb9c8:2025-05-14T23:03:49.882413+0000 - INFO - Request /auth/ successful ]
Log: [ec0b1be8-4a4a-47e0-a715-acc09616c1cf:2025-05-14T23:04:10.250851+0000 - INFO - Request /auth/token successful ]
Log: [f023cb9c-9200-47ef-97cc-6ea7aeb7e5cc:2025-05-14T23:04:22.732961+0000 - WARNING - /categories/ - request failed]
Log: [d29ecd20-5999-4c18-b52f-e9673e9086b4:2025-05-14T23:06:51.674322+0000 - INFO - Request /docs successful ]
Log: [9a15c0d7-3a87-4b6f-b324-0ef20c7159a1:2025-05-14T23:06:51.801369+0000 - INFO - Request /openapi.json successful ]
Log: [cbc5270b-52e0-40c9-b7d7-60b8df7dfd34:2025-05-14T23:19:25.275366+0000 - INFO - Request /docs successful ]
Log: [63c846a2-2b07-4bb0-99b0-aa8fb43cb8c0:2025-05-14T23:19:25.445114+0000 - INFO - Request /openapi.json successful ]
Log: [f5017754-4723-4f9f-b820-d556fae8a056:2025-05-14T23:23:36.918331+0000 - INFO - Request /auth/ successful ]
Log: [357ac313-3b91-4643-96f1-ac1b9a611946:2025-05-14T23:23:51.183000+0000 - INFO - Request /auth/token successful ]
Log: [9c106290-af95-49d1-9e0a-373557af19d4:2025-05-14T23:24:08.431105+0000 - INFO - Request /categories/ successful ]
Log: [5483e5d4-fdbf-45c9-9776-b88679cf22e7:2025-05-14T23:24:40.202104+0000 - INFO - Request /products/ successful ]
Log: [aeda63d3-ccbc-4973-b3c2-0f2c6bc84b48:2025-05-14T23:25:26.400619+0000 - INFO - Request /auth/read_current_user successful ]
Log: [b2999f8a-0f55-4ceb-a536-fb8328230ca9:2025-05-14T23:26:13.799472+0000 - INFO - Request /auth/ successful ]
Log: [00dc7fa9-32a6-4421-af09-c9a7c135e777:2025-05-14T23:26:24.158107+0000 - INFO - Request /auth/read_current_user successful ]
Log: [af13888e-d32c-4ee0-9992-eae19c94f073:2025-05-14T23:26:40.610629+0000 - INFO - Request /auth/users/Pop/make-admin successful ]
Log: [c5177983-bf3f-40b1-9119-1e93f973df01:2025-05-14T23:28:06.551258+0000 - INFO - Request /docs successful ]
Log: [8431ae5a-14ac-458d-bcf9-3005b9abe4d9:2025-05-14T23:28:06.629988+0000 - INFO - Request /openapi.json successful ]
Log: [83947886-8ee0-4ea6-8144-6c4dbf375025:2025-05-14T23:28:26.838875+0000 - WARNING - /auth/read_current_user - request failed]
Log: [436f840d-4345-47a3-99d7-0611a379c65c:2025-05-14T23:28:39.205781+0000 - WARNING - /auth/token - request failed]
Log: [c20f5e96-4081-42d9-9f0d-88b0393e8f20:2025-05-14T23:29:31.462920+0000 - INFO - Request /docs successful ]
Log: [08f25767-8a68-4bd8-bcbe-ee5611045235:2025-05-14T23:29:31.545460+0000 - INFO - Request /openapi.json successful ]
Log: [896fb26d-f614-474c-94aa-d4aebafe5d0c:2025-05-14T23:29:42.654099+0000 - WARNING - /auth/token - request failed]
Log: [dd96c59a-5807-40fd-a22d-d184e422ac7a:2025-05-14T23:29:42.666226+0000 - WARNING - /auth/token - request failed]
Log: [cf2c2186-3ff6-4ad0-ab2a-8d5b375d00dd:2025-05-14T23:30:22.053462+0000 - WARNING - /auth/token - request failed]
Log: [a508f2b1-d850-46b2-ab9c-24858bac4777:2025-05-14T23:31:41.776106+0000 - WARNING - /auth/token - request failed]
Log: [cd267dd3-d57a-4709-9e1a-42c190afcb6e:2025-05-14T23:35:17.014995+0000 - INFO - Request /docs successful ]
Log: [1f92d4eb-59cb-45f8-983d-3b58ee48bf3c:2025-05-14T23:35:17.151671+0000 - INFO - Request /openapi.json successful ]
Log: [a32ded4a-51a4-4f81-a878-bce34599519a:2025-05-14T23:35:33.805246+0000 - WARNING - /auth/token - request failed]
